### ISSUE TITLE
Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by bitzl** [EasyinnovaSL/Tiff-Library-4J#54]
For easy development and integration in CI/build systems it would be useful to get this library via Maven Central. Until then every developer would have to build the library themselves, same for every single CI build with most CI systems.

**Comment by victormunoz** [comment]
Hello!
The library is already published in Maven:
[https://mvnrepository.com/artifact/com.easyinnova/tifflibrary4java](https://mvnrepository.com/artifact/com.easyinnova/tifflibrary4java)
Regards
